
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.galerias DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.fotos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.etiquetas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cliente_etiquetas DISABLE ROW LEVEL SECURITY;
